# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  # AZ_NAME: 3fa49fd9-a2e6-4ae5-aef0-f0bc826d1fd1
  # AZ_PWD: gG-8Q~yglY1WulSMKiCLyNDf6lk7Lug-TckOWaK2
  # AZ_TENANT: 6f252721-a924-4a69-8cae-c936ad67fdae
  container_name: myblobcontainer
  file_to_upload: aspnet-get-started.zip
  blob_name: myblobstoragedemoaccount

steps:
 - task: SonarQubePrepare@5
   inputs:
     SonarQube: 'sonarqubetoken'
     scannerMode: 'MSBuild'
     projectKey: 'Learning_Learning_AYPvvpRxNGjNgKusi2G3'
     projectName: 'Learning'

 - task: NuGetToolInstaller@1

 - task: NuGetCommand@2
   inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'

 - task: VSBuild@1
   inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

 - task: SonarQubeAnalyze@5
 - task: SonarQubePublish@5
   inputs:
    pollingTimeoutSec: '30'
    
 - task: ExtractFiles@1
   inputs:
    archiveFilePatterns: '$(Build.ArtifactStagingDirectory)/*.zip'
    destinationFolder: '$(build.artifactStagingDirectory)'
    cleanDestinationFolder: false
    overwriteExistingFiles: false


#  - task: DotNetCoreCLI@1
#    inputs:
#     command: 'test'
#     projects: '**/aspnet-get-started.csproj'
#     arguments: '--configuration debug'

 - task: PublishBuildArtifacts@1
   inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

#  - task: AzureCLI@2
#    inputs:
#      azureSubscription: 'Free Trial (7efefb00-e17c-4d85-a4ce-d13264a86786)'
#      scriptType: 'bash'
#      scriptLocation: 'inlineScript'
#      inlineScript: |
#        az login --service-principal -u $(AZ_NAME) -p $(AZ_PWD) --tenant $(AZ_TENANT)
#        az storage blob upload --container-name $(container_name) --file $(file_to_upload) --name $(blob_name)

 - task: AzureFileCopy@1
   inputs:
     SourcePath: '$(Build.ArtifactStagingDirectory)'
     azureSubscription: 'Free Trial (7efefb00-e17c-4d85-a4ce-d13264a86786)'
     Destination: 'AzureBlob'
     storage: 'myblobstoragedemoaccount'
     ContainerName: 'myblobcontainer'